package uom.dialog.click2call.data;
// Generated Apr 23, 2013 12:19:36 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * AgentUsage generated by hbm2java
 */
public class AgentUsage  implements java.io.Serializable {


     private Integer id;
     private Agents agents;
     private Integer usedSeconds;
     private Date resetDate;

    public AgentUsage() {
    }

	
    public AgentUsage(Integer id) {
        this.id = id;
    }
    public AgentUsage(Integer id, Agents agents, Integer usedSeconds, Date resetDate) {
       this.id = id;
       this.agents = agents;
       this.usedSeconds = usedSeconds;
       this.resetDate = resetDate;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Agents getAgents() {
        return this.agents;
    }
    
    public void setAgents(Agents agents) {
        this.agents = agents;
    }
    public Integer getUsedSeconds() {
        return this.usedSeconds;
    }
    
    public void setUsedSeconds(Integer usedSeconds) {
        this.usedSeconds = usedSeconds;
    }
    public Date getResetDate() {
        return this.resetDate;
    }
    
    public void setResetDate(Date resetDate) {
        this.resetDate = resetDate;
    }




}


