package uom.dialog.click2call.data;
// Generated Apr 8, 2013 10:35:36 AM by Hibernate Tools 3.2.1.GA

import org.springframework.stereotype.Component;




/**
 * Blacklist generated by hbm2java
 */
@Component
public class Blacklist  implements java.io.Serializable {


     private Integer recId;
     private Company company;
     private String number;

    public Blacklist() {
    }

    public Blacklist(Company company, String number) {
       this.company = company;
       this.number = number;
    }
   
    public Integer getRecId() {
        return this.recId;
    }
    
    public void setRecId(Integer recId) {
        this.recId = recId;
    }
    public Company getCompany() {
        return this.company;
    }
    
    public void setCompany(Company company) {
        this.company = company;
    }
    public String getNumber() {
        return this.number;
    }
    
    public void setNumber(String number) {
        this.number = number;
    }




}


