package uom.dialog.click2call.data;
// Generated Apr 8, 2013 10:35:36 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import org.springframework.stereotype.Component;

/**
 * Calls generated by hbm2java
 */
@Component
public class Calls  implements java.io.Serializable {


     private Integer callId;
     private Agents agents;
     private String customerNumber;
     private Date startTime;
     private Date endTime;
     private Double callCharge;
     private String callCorrelator;
     private int status;

    public Calls() {
    }

	
    public Calls(Agents agents, String customerNumber, Date startTime, String callCorrelator, int status) {
        this.agents = agents;
        this.customerNumber = customerNumber;
        this.startTime = startTime;
        this.callCorrelator = callCorrelator;
        this.status = status;
    }
    public Calls(Agents agents, String customerNumber, Date startTime, Date endTime, Double callCharge, String callCorrelator, int status) {
       this.agents = agents;
       this.customerNumber = customerNumber;
       this.startTime = startTime;
       this.endTime = endTime;
       this.callCharge = callCharge;
       this.callCorrelator = callCorrelator;
       this.status = status;
    }
   
    public Integer getCallId() {
        return this.callId;
    }
    
    public void setCallId(Integer callId) {
        this.callId = callId;
    }
    public Agents getAgents() {
        return this.agents;
    }
    
    public void setAgents(Agents agents) {
        this.agents = agents;
    }
    public String getCustomerNumber() {
        return this.customerNumber;
    }
    
    public void setCustomerNumber(String customerNumber) {
        this.customerNumber = customerNumber;
    }
    public Date getStartTime() {
        return this.startTime;
    }
    
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }
    public Date getEndTime() {
        return this.endTime;
    }
    
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }
    public Double getCallCharge() {
        return this.callCharge;
    }
    
    public void setCallCharge(Double callCharge) {
        this.callCharge = callCharge;
    }
    public String getCallCorrelator() {
        return this.callCorrelator;
    }
    
    public void setCallCorrelator(String callCorrelator) {
        this.callCorrelator = callCorrelator;
    }
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }




}


