package uom.dialog.click2call.data;
// Generated Apr 8, 2013 10:35:36 AM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;
import org.springframework.stereotype.Component;

/**
 * ChargingPlan generated by hbm2java
 */
@Component
public class ChargingPlan implements java.io.Serializable {

    private Integer planId;
    private ChargingType chargingType;
    private String name;
    private Double monthlyRental;
    private Integer allocatedMinutes;
    private Double perminuteCharge;
    private Set companies = new HashSet(0);

    public ChargingPlan() {
    }

    public ChargingPlan(ChargingType chargingType, String name) {
        this.chargingType = chargingType;
        this.name = name;
    }

    public ChargingPlan(ChargingType chargingType, String name, Double monthlyRental, Integer allocatedMinutes, Double perminuteCharge, Set companies) {
        this.chargingType = chargingType;
        this.name = name;
        this.monthlyRental = monthlyRental;
        this.allocatedMinutes = allocatedMinutes;
        this.perminuteCharge = perminuteCharge;
        this.companies = companies;
    }

    public Integer getPlanId() {
        return this.planId;
    }

    public void setPlanId(Integer planId) {
        this.planId = planId;
    }

    public ChargingType getChargingType() {
        return this.chargingType;
    }

    public void setChargingType(ChargingType chargingType) {
        this.chargingType = chargingType;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Double getMonthlyRental() {
        return this.monthlyRental;
    }

    public void setMonthlyRental(Double monthlyRental) {
        this.monthlyRental = monthlyRental;
    }

    public Integer getAllocatedMinutes() {
        return this.allocatedMinutes;
    }

    public void setAllocatedMinutes(Integer allocatedMinutes) {
        this.allocatedMinutes = allocatedMinutes;
    }

    public Double getPerminuteCharge() {
        return this.perminuteCharge;
    }

    public void setPerminuteCharge(Double perminuteCharge) {
        this.perminuteCharge = perminuteCharge;
    }

    public Set getCompanies() {
        return this.companies;
    }

    public void setCompanies(Set companies) {
        this.companies = companies;
    }
}
