package uom.dialog.click2call.data;
// Generated Apr 23, 2013 12:19:36 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * CompanyUsage generated by hbm2java
 */
public class CompanyUsage  implements java.io.Serializable {


     private Integer id;
     private Company company;
     private Integer usedSeconds;
     private Date resetDate;

    public CompanyUsage() {
    }

    public CompanyUsage(Integer id, Company company, Integer usedSeconds, Date resetDate) {
       this.id = id;
       this.company = company;
       this.usedSeconds = usedSeconds;
       this.resetDate = resetDate;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Company getCompany() {
        return this.company;
    }
    
    public void setCompany(Company company) {
        this.company = company;
    }
    public double getUsedSeconds() {
        return this.usedSeconds;
    }
    
    public void setUsedSeconds(Integer usedSeconds) {
        this.usedSeconds = usedSeconds;
    }
    public Date getResetDate() {
        return this.resetDate;
    }
    
    public void setResetDate(Date resetDate) {
        this.resetDate = resetDate;
    }




}


