package uom.dialog.click2call.data;
// Generated Apr 10, 2013 11:50:53 AM by Hibernate Tools 3.2.1.GA



/**
 * MasterData generated by hbm2java
 */
public class MasterData  implements java.io.Serializable {


     private Integer id;
     private String type;
     private String value;
     private String description;

    public MasterData() {
    }

    public MasterData(String type, String value, String description) {
       this.type = type;
       this.value = value;
       this.description = description;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


