package uom.dialog.click2call.data;
// Generated Jun 18, 2013 2:34:07 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import org.springframework.stereotype.Component;

/**
 * SystemHistory generated by hbm2java
 */
@Component
public class SystemHistory  implements java.io.Serializable {


     private Integer id;
     private Users users;
     private String tableName;
     private String changeField;
     private String tablePk;
     private String oldValue;
     private String newValue;
     private Date changeDate;

    public SystemHistory() {
    }

    public SystemHistory(Users users, String tableName, String changeField, String tablePk, String oldValue, String newValue, Date changeDate) {
       this.users = users;
       this.tableName = tableName;
       this.changeField = changeField;
       this.tablePk = tablePk;
       this.oldValue = oldValue;
       this.newValue = newValue;
       this.changeDate = changeDate;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public String getTableName() {
        return this.tableName;
    }
    
    public void setTableName(String tableName) {
        this.tableName = tableName;
    }
    public String getChangeField() {
        return this.changeField;
    }
    
    public void setChangeField(String changeField) {
        this.changeField = changeField;
    }
    public String getTablePk() {
        return this.tablePk;
    }
    
    public void setTablePk(String tablePk) {
        this.tablePk = tablePk;
    }
    public String getOldValue() {
        return this.oldValue;
    }
    
    public void setOldValue(String oldValue) {
        this.oldValue = oldValue;
    }
    public String getNewValue() {
        return this.newValue;
    }
    
    public void setNewValue(String newValue) {
        this.newValue = newValue;
    }
    public Date getChangeDate() {
        return this.changeDate;
    }
    
    public void setChangeDate(Date changeDate) {
        this.changeDate = changeDate;
    }




}


