package uom.dialog.click2call.data;
// Generated Apr 8, 2013 10:35:36 AM by Hibernate Tools 3.2.1.GA

import org.springframework.stereotype.Component;




/**
 * TypePrivileges generated by hbm2java
 */
@Component
public class TypePrivileges  implements java.io.Serializable {


     private Integer tpId;
     private UserType userType;
     private Privileges privileges;

    public TypePrivileges() {
    }

    public TypePrivileges(UserType userType, Privileges privileges) {
       this.userType = userType;
       this.privileges = privileges;
    }
   
    public Integer getTpId() {
        return this.tpId;
    }
    
    public void setTpId(Integer tpId) {
        this.tpId = tpId;
    }
    public UserType getUserType() {
        return this.userType;
    }
    
    public void setUserType(UserType userType) {
        this.userType = userType;
    }
    public Privileges getPrivileges() {
        return this.privileges;
    }
    
    public void setPrivileges(Privileges privileges) {
        this.privileges = privileges;
    }




}


