package uom.dialog.click2call.data;
// Generated Apr 8, 2013 10:35:36 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import org.springframework.stereotype.Component;

/**
 * UserType generated by hbm2java
 */
@Component
public class UserType  implements java.io.Serializable {


     private Integer typeId;
     private String typeName;
     private Set userses = new HashSet(0);
     private Set typePrivilegeses = new HashSet(0);

    public UserType() {
    }

	
    public UserType(String typeName) {
        this.typeName = typeName;
    }
    public UserType(String typeName, Set userses, Set typePrivilegeses) {
       this.typeName = typeName;
       this.userses = userses;
       this.typePrivilegeses = typePrivilegeses;
    }
   
    public Integer getTypeId() {
        return this.typeId;
    }
    
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }
    public String getTypeName() {
        return this.typeName;
    }
    
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }
    public Set getUserses() {
        return this.userses;
    }
    
    public void setUserses(Set userses) {
        this.userses = userses;
    }
    public Set getTypePrivilegeses() {
        return this.typePrivilegeses;
    }
    
    public void setTypePrivilegeses(Set typePrivilegeses) {
        this.typePrivilegeses = typePrivilegeses;
    }




}


