/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package uom.dialog.click2call.dto;

import org.springframework.stereotype.Component;
import uom.dialog.click2call.data.Company;

/**
 *
 * @author Hasala
 * ©Dialog - University of Moratuwa Mobile Communications Research Laboratory
 */
@Component
public class AgentDTO {
    private String companyName; // Agent's Company
    private String agentName; // Agent Name
    private String agentKey; // Agent Key, Generated by System
    private String agentNumber; // Agent Contact Number
    private Integer agentStatus; //Status of the Agent (1=Enabled, 0=Disabled)
    private Company company; //Agent's Company
    private Integer totalMinutes; //Total minutes per agent
    private Double usedMinutes; //Used Minutes
    private Integer agentId; //agent Id
    private Integer companyId;

    public Integer getAgentId() {
        return agentId;
    }

    public void setAgentId(Integer agentId) {
        this.agentId = agentId;
    }

    public String getCompanyName(){
        return companyName;
    }
    public void setCompanyName(String companyName){
        this.companyName = companyName;
    }
    public String getAgentName(){
        return agentName;
    }
    public void setAgentName(String agentName){
        this.agentName = agentName;
    }
    public String getAgentKey(){
        return agentKey;
    }
    public void setAgentKey(String agentKey){
        this.agentKey = agentKey;
    }
    public String getAgentNumber(){
        return agentNumber;
    }
    public void setAgentNumber(String agentNumber){
        this.agentNumber = agentNumber;
    }
    public Integer getAgentStatus(){
        return agentStatus;
    }
    public void setAgentStatus(Integer agentStatus){
        this.agentStatus = agentStatus;
    }

    public Company getCompany() {
        return company;
    }

    public void setCompany(Company company) {
        this.company = company;
    }

    public Integer getTotalMinutes() {
        return totalMinutes;
    }

    public void setTotalMinutes(Integer totalMinutes) {
        this.totalMinutes = totalMinutes;
    }

    public Double getUsedMinutes() {
        return usedMinutes;
    }

    public void setUsedMinutes(Double usedMinutes) {
        this.usedMinutes = usedMinutes;
    }

    public Integer getCompanyId() {
        return companyId;
    }

    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }
    
    
}
